// src/app/layout.tsx
import type { Metadata } from "next";
import { Fredoka, Noto_Sans_TC } from "next/font/google";
import "./globals.css";

const fredoka = Fredoka({
  subsets: ["latin"],
  variable: "--font-fredoka",
});

const notoSansTC = Noto_Sans_TC({
  subsets: ["latin"], // Adjusted subset to latin as per Google Fonts standard for Next.js, or use 'preload: false'
  weight: ["400"],
  variable: "--font-noto-sans-tc",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${fredoka.variable} ${notoSansTC.variable}`}>
        {children}
      </body>
    </html>
  );
}
